CREATE TABLE "faucet_usages" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "faucet_usages_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"address" "citext" NOT NULL,
	"requested_at" timestamp DEFAULT now() NOT NULL
);
